name: maccman
favicon: null
layout_spectrum: 0.29381021670997143
typography_spectrum: 0.5679800377693027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#777576'
    - '#3e3c3d'
    - '#070606'
    - '#d2242e'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.0954312696121633
  rhythmicContrast: 0.75
purpose: []
